set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_a_pad_o[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_a_pad_o[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_a_pad_o[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_a_pad_o[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_a_pad_o[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_a_pad_o[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_a_pad_o[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_a_pad_o[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_a_pad_o[8]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_a_pad_o[9]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_a_pad_o[10]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_a_pad_o[11]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_dq_pad_io[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_dq_pad_io[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_dq_pad_io[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_dq_pad_io[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_dq_pad_io[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_dq_pad_io[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_dq_pad_io[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_dq_pad_io[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_dq_pad_io[8]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_dq_pad_io[9]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_dq_pad_io[10]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_dq_pad_io[11]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_dq_pad_io[12]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_dq_pad_io[13]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_dq_pad_io[14]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_dq_pad_io[15]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_dqm_pad_o[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_dqm_pad_o[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_ba_pad_o[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_ba_pad_o[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_cas_pad_o
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_cke_pad_o
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_cs_n_pad_o
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_ras_pad_o
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_we_pad_o
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to video_sdram_clk_pad_o

set_location_assignment PIN_T10 -to video_sdram_a_pad_o[0]
set_location_assignment PIN_R12 -to video_sdram_a_pad_o[1]
set_location_assignment PIN_R13 -to video_sdram_a_pad_o[2]
set_location_assignment PIN_T14 -to video_sdram_a_pad_o[3]
set_location_assignment PIN_A12 -to video_sdram_a_pad_o[4]
set_location_assignment PIN_D12 -to video_sdram_a_pad_o[5]
set_location_assignment PIN_B12 -to video_sdram_a_pad_o[6]
set_location_assignment PIN_D11 -to video_sdram_a_pad_o[7]
set_location_assignment PIN_C11 -to video_sdram_a_pad_o[8]
set_location_assignment PIN_E11 -to video_sdram_a_pad_o[9]
set_location_assignment PIN_P11 -to video_sdram_a_pad_o[10]
set_location_assignment PIN_C9 -to video_sdram_a_pad_o[11]
set_location_assignment PIN_N14 -to video_sdram_dq_pad_io[0]
set_location_assignment PIN_K15 -to video_sdram_dq_pad_io[1]
set_location_assignment PIN_J13 -to video_sdram_dq_pad_io[2]
set_location_assignment PIN_M10 -to video_sdram_dq_pad_io[3]
set_location_assignment PIN_C8 -to video_sdram_dq_pad_io[4]
set_location_assignment PIN_B7 -to video_sdram_dq_pad_io[5]
set_location_assignment PIN_A5 -to video_sdram_dq_pad_io[6]
set_location_assignment PIN_B3 -to video_sdram_dq_pad_io[7]
set_location_assignment PIN_L13 -to video_sdram_dq_pad_io[8]
set_location_assignment PIN_J14 -to video_sdram_dq_pad_io[9]
set_location_assignment PIN_J16 -to video_sdram_dq_pad_io[10]
set_location_assignment PIN_L14 -to video_sdram_dq_pad_io[11]
set_location_assignment PIN_A7 -to video_sdram_dq_pad_io[12]
set_location_assignment PIN_B6 -to video_sdram_dq_pad_io[13]
set_location_assignment PIN_A4 -to video_sdram_dq_pad_io[14]
set_location_assignment PIN_A2 -to video_sdram_dq_pad_io[15]
set_location_assignment PIN_E7 -to video_sdram_dqm_pad_o[0]
set_location_assignment PIN_N15 -to video_sdram_dqm_pad_o[1]
set_location_assignment PIN_N9 -to video_sdram_ba_pad_o[0]
set_location_assignment PIN_N12 -to video_sdram_ba_pad_o[1]
set_location_assignment PIN_P15 -to video_sdram_cas_pad_o
set_location_assignment PIN_F9 -to video_sdram_cke_pad_o
set_location_assignment PIN_L16 -to video_sdram_cs_n_pad_o
set_location_assignment PIN_R16 -to video_sdram_ras_pad_o
set_location_assignment PIN_R14 -to video_sdram_we_pad_o
set_location_assignment PIN_E8 -to video_sdram_clk_pad_o
