ba12_ip:
	cat ../../ba12/rtl/verilog/ba12_top_ip.v ../../debug_if/rtl/verilog/dbg_top_ip.v ../../tap/rtl/verilog/tap_ip.v or1k_top.v > or1k_top_ip.v

or1200_ip:
	cat ../../or1200/rtl/verilog/or1200_top_ip.v ../../debug_if/rtl/verilog/dbg_top_ip.v ../../tap/rtl/verilog/tap_ip.v or1k_top.v > or1200.v

or1200r2_ip:
	cat ../../or1200r2/rtl/verilog/or1200_top_ip.v ../../debug_if/rtl/verilog/dbg_top_ip.v ../../tap/rtl/verilog/tap_ip.v or1k_top.v > or1200r2.v

all: or1200_ip or1200r2_ip ba12_ip
